version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "08:00"
      timezone: Australia/Melbourne

  # Python dependencies managed by Poetry
  - package-ecosystem: poetry
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "08:00"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 1
