name: Build and Test

on:
  push:
    paths-ignore:
      - '**.json'
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint on workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: pip install poetry
      - name: Install yamllint
        run: poetry install --only dev
      - name: Run yamllint
        run: make yamllint

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make install-test-deps

      - name: Run tests with coverage
        run: make test-coverage

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.13'
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
